In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta
#data = yf.download(tickers = '^RUI', start = '2012-03-11',end = '2022-07-10')
data = yf.download(tickers='BTC-usd', priod= 'max',interval='1d')
#data.head(10)
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...
2022-12-24,16796.976562,16864.703125,16793.527344,16847.755859,16847.755859,9744636213
2022-12-25,16847.505859,16860.554688,16755.253906,16841.986328,16841.986328,11656379938
2022-12-26,16842.250000,16920.123047,16812.369141,16919.804688,16919.804688,11886957804
2022-12-27,16919.291016,16959.845703,16642.072266,16717.173828,16717.173828,15748580239
2022-12-28,16716.972656,16767.767578,16500.519531,16503.671875,16503.671875,16784441344

In [2]:
# Adding indicators
data['RSI']=ta.rsi(data.Close, length=15)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)

data['Target'] = data['Adj Close']-data.Open
data['Target'] = data['Target'].shift(-1)

data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace=True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close', 'Date'], axis=1, inplace=True)

In [3]:
data_set = data.iloc[:, 0:11]#.values
pd.set_option('display.max_columns', None)

#data_set.head(20)
data_set
#print(data_set.shape)
#print(data.shape)
#print(type(data_set))

,Open,High,Low,Adj Close,RSI,EMAF,EMAM,EMAS,Target,TargetClass,TargetNextClose
0,221.968994,240.259003,221.261993,235.427002,50.019072,229.312807,288.640505,327.932773,21.793015,1,257.321014
1,235.528000,259.808014,235.528000,257.321014,58.174526,231.980256,288.020317,326.997518,-22.681992,0,234.824997
2,257.506989,265.610992,227.684006,234.824997,49.315763,232.251183,286.966944,325.776690,-0.981995,0,233.843002
3,234.824997,239.520996,229.022003,233.843002,48.967016,232.402785,285.914985,324.559025,10.188004,1,243.610001
4,233.421997,245.774994,232.313995,243.610001,52.543343,233.470139,285.077263,323.486853,-7.453995,0,236.326004
...,...,...,...,...,...,...,...,...,...,...,...
2870,16829.644531,16905.218750,16794.458984,16796.953125,46.097985,16958.027640,18560.419901,20125.263915,50.779297,1,16847.755859
2871,16796.976562,16864.703125,16793.527344,16847.755859,46.916068,16947.525565,18526.505762,20081.853213,-5.519531,0,16841.986328
2872,16847.505859,16860.554688,16755.253906,16841.986328,46.829585,16937.474209,18493.148941,20038.941068,77.554688,1,16919.804688
2873,16842.250000,16920.123047,16812.369141,16919.804688,48.209222,16935.791398,18461.993610,19997.628004,-202.117188,0,16717.173828
2874,16919.291016,16959.845703,16642.072266,16717.173828,44.954914,16914.970677,18427.442723,19954.178280,-213.300781,0,16503.671875

In [4]:
#Target column Categories
#y =[1 if data.Open[i]>data.Close[i] else 0 for i in range(0, len(data))]
#yi = [data.Open[i]-data.Close[i] for i in range(0, len(data))]
#print(yi)
#print(len(yi))

In [5]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(-1,1))
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)

[[-0.99964654 -0.99952087 -0.99934439 ...  0.02003178  1.
  -0.9986096 ]
 [-0.99924383 -0.99895064 -0.99891328 ...  0.0140514  -1.
  -0.99927757]
 [-0.99859105 -0.99878137 -0.99915032 ...  0.01696932 -1.
  -0.99930673]
 ...
 [-0.50586515 -0.51472239 -0.4996959  ...  0.02752984  1.
  -0.50385334]
 [-0.50602125 -0.51298484 -0.49796991 ... -0.01007656 -1.
  -0.50987003]
 [-0.50373312 -0.51182617 -0.50311619 ... -0.01158037 -1.
  -0.5162095 ]]

In [6]:
# multiple feature from data provided to the model
X = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 180
print(data_set_scaled.shape[0])
for j in range(8):#data_set_scaled[0].size):#2 columns are target not X
    X.append([])
    for i in range(backcandles, data_set_scaled.shape[0]):#backcandles+2
        X[j].append(data_set_scaled[i-backcandles:i, j])

#move axis from 0 to position 2
X=np.moveaxis(X, [0], [2])

#Erase first elements of y because of backcandles to match X length
#del(yi[0:backcandles])
#X, yi = np.array(X), np.array(yi)
# Choose -1 for last column, classification else -2...
X, yi =np.array(X), np.array(data_set_scaled[backcandles:,-1])
y=np.reshape(yi,(len(yi),1))
#y=sc.fit_transform(yi)
#X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X)
print(X.shape)
print(y)
print(y.shape)

2875
[[[-0.99964654 -0.99952087 -0.99934439 ... -1.         -0.99829104
   -0.99697281]
  [-0.99924383 -0.99895064 -0.99891328 ... -0.99991529 -0.9983137
   -0.99700873]
  [-0.99859105 -0.99878137 -0.99915032 ... -0.99990669 -0.99835219
   -0.99705562]
  ...
  [-0.99848387 -0.99874077 -0.9981596  ... -0.99843037 -0.99920992
   -0.99937771]
  [-0.99835431 -0.99873992 -0.9980953  ... -0.99847353 -0.99920921
   -0.99937814]
  [-0.99838805 -0.99864209 -0.99805003 ... -0.99849468 -0.99920424
   -0.99937555]]

 [[-0.99924383 -0.99895064 -0.99891328 ... -0.99991529 -0.9983137
   -0.99700873]
  [-0.99859105 -0.99878137 -0.99915032 ... -0.99990669 -0.99835219
   -0.99705562]
  [-0.99926471 -0.9995424  -0.99910989 ... -0.99990187 -0.99839063
   -0.99710238]
  ...
  [-0.99835431 -0.99873992 -0.9980953  ... -0.99847353 -0.99920921
   -0.99937814]
  [-0.99838805 -0.99864209 -0.99805003 ... -0.99849468 -0.99920424
   -0.99937555]
  [-0.99820225 -0.99863372 -0.99800848 ... -0.99852595 -0.99920227
   -0.99937504]]

 [[-0.99859105 -0.99878137 -0.99915032 ... -0.99990669 -0.99835219
   -0.99705562]
  [-0.99926471 -0.9995424  -0.99910989 ... -0.99990187 -0.99839063
   -0.99710238]
  [-0.99930638 -0.99935997 -0.9990104  ... -0.99986798 -0.99842124
   -0.99714356]
  ...
  [-0.99838805 -0.99864209 -0.99805003 ... -0.99849468 -0.99920424
   -0.99937555]
  [-0.99820225 -0.99863372 -0.99800848 ... -0.99852595 -0.99920227
   -0.99937504]
  [-0.99833337 -0.99876326 -0.99808789 ... -0.99856119 -0.99920199
   -0.9993757 ]]

 ...

 [[-0.39050851 -0.38918256 -0.3947268  ... -0.28807657  0.14519231
    0.31973977]
  [-0.40388472 -0.41252561 -0.40352131 ... -0.29576892  0.13688721
    0.3123595 ]
  [-0.40901862 -0.4190302  -0.44003051 ... -0.30369436  0.12851554
    0.30491456]
  ...
  [-0.50673017 -0.5145439  -0.50461701 ... -0.46821402 -0.32931821
   -0.23493953]
  [-0.50639564 -0.51341959 -0.49851114 ... -0.46875246 -0.33062001
   -0.23665529]
  [-0.50736588 -0.51460139 -0.4985393  ... -0.46908597 -0.33185927
   -0.23832248]]

 [[-0.40388472 -0.41252561 -0.40352131 ... -0.29576892  0.13688721
    0.3123595 ]
  [-0.40901862 -0.4190302  -0.44003051 ... -0.30369436  0.12851554
    0.30491456]
  [-0.41756757 -0.40469327 -0.42963341 ... -0.31242367  0.11993673
    0.29730607]
  ...
  [-0.50639564 -0.51341959 -0.49851114 ... -0.46875246 -0.33062001
   -0.23665529]
  [-0.50736588 -0.51460139 -0.4985393  ... -0.46908597 -0.33185927
   -0.23832248]
  [-0.50586515 -0.51472239 -0.4996959  ... -0.46940517 -0.33307816
   -0.23997052]]

 [[-0.40901862 -0.4190302  -0.44003051 ... -0.30369436  0.12851554
    0.30491456]
  [-0.41756757 -0.40469327 -0.42963341 ... -0.31242367  0.11993673
    0.29730607]
  [-0.43377302 -0.44147323 -0.43104246 ... -0.32040361  0.11150818
    0.28978457]
  ...
  [-0.50736588 -0.51460139 -0.4985393  ... -0.46908597 -0.33185927
   -0.23832248]
  [-0.50586515 -0.51472239 -0.4996959  ... -0.46940517 -0.33307816
   -0.23997052]
  [-0.50602125 -0.51298484 -0.49796991 ... -0.46945861 -0.33421661
   -0.24155715]]]
(2695, 180, 8)
[[-0.99840891]
 [-0.9983614 ]
 [-0.998484  ]
 ...
 [-0.50385334]
 [-0.50987003]
 [-0.5162095 ]]
(2695, 1)

In [7]:
#also comprehensions for X
#X = np.array([data_set_scaled[i-backcandles:i,:4].copy() for i in range(backcandles,len(data_set_scaled))])
#print(X)
#print(X.shape)

In [8]:
# split data into train test sets
splitlimit = int(len(X)*0.8)
print(splitlimit)
X_train, X_test = X[:splitlimit], X[splitlimit:]
y_train, y_test = y[:splitlimit], y[splitlimit:]
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y_train.shape)

2156
(2156, 180, 8)
(539, 180, 8)
(2156, 1)
(539, 1)
(2156, 1)

In [9]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed

import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np
#tf.random.set_seed(20)
np.random.seed(10)

lstm_input = Input(shape=(backcandles, 8), name='lstm_input')
inputs = LSTM(100, name='first_layer')(lstm_input)
inputs = Dense(1, name='dense_layer')(inputs)
output = Activation('linear', name='output')(inputs)
model = Model(inputs=lstm_input, outputs=output)
adam = optimizers.Adam()
model.compile(optimizer=adam, loss="mean_squared_error")
print(model.summary())
model.fit(x=X_train, y=y_train, batch_size=32, epochs=50, shuffle=True, validation_split = 0.1)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_input (InputLayer)     [(None, 180, 8)]          0

 first_layer (LSTM)          (None, 100)               43600

 dense_layer (Dense)         (None, 1)                 101

 output (Activation)         (None, 1)                 0

=================================================================
Total params: 43,701
Trainable params: 43,701
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/50
61/61 [==============================] - 24s 231ms/step - loss: 0.0948 - val_loss: 0.0470
Epoch 2/50
61/61 [==============================] - 12s 194ms/step - loss: 0.0016 - val_loss: 0.0441
Epoch 3/50
61/61 [==============================] - 12s 200ms/step - loss: 9.9174e-04 - val_loss: 0.0433
Epoch 4/50
61/61 [==============================] - 12s 195ms/step - loss: 7.0231e-04 - val_loss: 0.0433
Epoch 5/50
61/61 [==============================] - 13s 213ms/step - loss: 5.5832e-04 - val_loss: 0.0429
Epoch 6/50
61/61 [==============================] - 14s 223ms/step - loss: 4.9958e-04 - val_loss: 0.0411
Epoch 7/50
61/61 [==============================] - 13s 209ms/step - loss: 4.5209e-04 - val_loss: 0.0399
Epoch 8/50
61/61 [==============================] - 12s 201ms/step - loss: 4.1531e-04 - val_loss: 0.0390
Epoch 9/50
61/61 [==============================] - 12s 197ms/step - loss: 3.9158e-04 - val_loss: 0.0378
Epoch 10/50
61/61 [==============================] - 12s 197ms/step - loss: 3.7701e-04 - val_loss: 0.0367
Epoch 11/50
61/61 [==============================] - 12s 197ms/step - loss: 3.4004e-04 - val_loss: 0.0363
Epoch 12/50
61/61 [==============================] - 12s 195ms/step - loss: 3.3363e-04 - val_loss: 0.0355
Epoch 13/50
61/61 [==============================] - 12s 197ms/step - loss: 3.1815e-04 - val_loss: 0.0353
Epoch 14/50
61/61 [==============================] - 12s 202ms/step - loss: 2.9929e-04 - val_loss: 0.0351
Epoch 15/50
61/61 [==============================] - 12s 200ms/step - loss: 3.1182e-04 - val_loss: 0.0353
Epoch 16/50
61/61 [==============================] - 12s 201ms/step - loss: 3.1835e-04 - val_loss: 0.0340
Epoch 17/50
61/61 [==============================] - 12s 196ms/step - loss: 3.0320e-04 - val_loss: 0.0351
Epoch 18/50
61/61 [==============================] - 12s 201ms/step - loss: 2.9747e-04 - val_loss: 0.0350
Epoch 19/50
61/61 [==============================] - 13s 219ms/step - loss: 2.8944e-04 - val_loss: 0.0351
Epoch 20/50
61/61 [==============================] - 13s 211ms/step - loss: 2.8946e-04 - val_loss: 0.0354
Epoch 21/50
61/61 [==============================] - 13s 215ms/step - loss: 2.9307e-04 - val_loss: 0.0352
Epoch 22/50
61/61 [==============================] - 13s 209ms/step - loss: 3.1007e-04 - val_loss: 0.0348
Epoch 23/50
61/61 [==============================] - 13s 220ms/step - loss: 3.0521e-04 - val_loss: 0.0355
Epoch 24/50
61/61 [==============================] - 13s 215ms/step - loss: 2.6688e-04 - val_loss: 0.0357
Epoch 25/50
61/61 [==============================] - 12s 200ms/step - loss: 2.7138e-04 - val_loss: 0.0362
Epoch 26/50
61/61 [==============================] - 12s 197ms/step - loss: 2.7000e-04 - val_loss: 0.0361
Epoch 27/50
61/61 [==============================] - 13s 205ms/step - loss: 2.6212e-04 - val_loss: 0.0359
Epoch 28/50
61/61 [==============================] - 12s 204ms/step - loss: 2.8353e-04 - val_loss: 0.0375
Epoch 29/50
61/61 [==============================] - 12s 197ms/step - loss: 2.8299e-04 - val_loss: 0.0377
Epoch 30/50
61/61 [==============================] - 12s 203ms/step - loss: 3.2026e-04 - val_loss: 0.0364
Epoch 31/50
61/61 [==============================] - 12s 201ms/step - loss: 2.6686e-04 - val_loss: 0.0376
Epoch 32/50
61/61 [==============================] - 12s 199ms/step - loss: 2.6953e-04 - val_loss: 0.0372
Epoch 33/50
61/61 [==============================] - 12s 197ms/step - loss: 2.5865e-04 - val_loss: 0.0372
Epoch 34/50
61/61 [==============================] - 12s 199ms/step - loss: 2.5279e-04 - val_loss: 0.0381
Epoch 35/50
61/61 [==============================] - 12s 195ms/step - loss: 2.6077e-04 - val_loss: 0.0388
Epoch 36/50
61/61 [==============================] - 12s 196ms/step - loss: 2.6384e-04 - val_loss: 0.0379
Epoch 37/50
61/61 [==============================] - 12s 197ms/step - loss: 2.5817e-04 - val_loss: 0.0384
Epoch 38/50
61/61 [==============================] - 12s 198ms/step - loss: 2.5239e-04 - val_loss: 0.0392
Epoch 39/50
61/61 [==============================] - 12s 198ms/step - loss: 2.5720e-04 - val_loss: 0.0380
Epoch 40/50
61/61 [==============================] - 12s 197ms/step - loss: 2.6364e-04 - val_loss: 0.0388
Epoch 41/50
61/61 [==============================] - 12s 202ms/step - loss: 2.5041e-04 - val_loss: 0.0387
Epoch 42/50
61/61 [==============================] - 12s 198ms/step - loss: 2.4663e-04 - val_loss: 0.0400
Epoch 43/50
61/61 [==============================] - 13s 209ms/step - loss: 2.5601e-04 - val_loss: 0.0402
Epoch 44/50
61/61 [==============================] - 13s 206ms/step - loss: 2.6386e-04 - val_loss: 0.0400
Epoch 45/50
61/61 [==============================] - 13s 210ms/step - loss: 2.4081e-04 - val_loss: 0.0396
Epoch 46/50
61/61 [==============================] - 13s 208ms/step - loss: 2.6226e-04 - val_loss: 0.0396
Epoch 47/50
61/61 [==============================] - 13s 211ms/step - loss: 2.6426e-04 - val_loss: 0.0404
Epoch 48/50
61/61 [==============================] - 13s 205ms/step - loss: 2.5464e-04 - val_loss: 0.0397
Epoch 49/50
61/61 [==============================] - 12s 198ms/step - loss: 2.2691e-04 - val_loss: 0.0403
Epoch 50/50
61/61 [==============================] - 12s 198ms/step - loss: 2.4314e-04 - val_loss: 0.0408

In [10]:
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
for i in range(10):
   print(y_pred[i], y_test[i])

17/17 [==============================] - 2s 76ms/step
[-0.06674043] [-0.03002807]
[-0.0691288] [-0.00269165]
[-0.07954112] [-0.01093118]
[-0.08071733] [0.0104378]
[-0.08294454] [-0.02175932]
[-0.0782081] [-0.03523458]
[-0.08314992] [-0.03166188]
[-0.09129575] [-0.06259043]
[-0.09735923] [-0.07325584]
[-0.11034627] [-0.06994422]

In [11]:
def MAPE(Y_actual,Y_Predicted):
    mape = np.mean(np.abs((Y_actual - Y_Predicted)/Y_actual))*100
    return mape
print("the MAPE is : ", MAPE(y_test,y_pred))

the MAPE is :  52.129596374886155

In [1]:
plt.figure(figsize=(8,8))
plt.plot(y_test, color = 'blue', label = 'Test')
plt.plot(y_pred, color = 'red', label = 'pred')
plt.legend()
plt.show()

NameError: name 'plt' is not defined